# Generated by Django 6.1 on 2026-09-07 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_cliente_empresa_interaccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='etapa',
            new_name='etapa_crm',
        ),
    ]
